language: ruby
rvm:
  - 2.1
install:
  - gem install jekyll
  - gem install github-pages
  - gem install html-proofer
before_script:
  # Replace with the line that travis encrypt-file printed out
  -  openssl aes-256-cbc -K $encrypted_e9678b4a945e_key -iv $encrypted_e9678b4a945e_iv -in .key.enc -out .key -d
  - chmod go-rwx .key
  - eval `ssh-agent -s`
  - ssh-add .key
  - git config user.name "Travis-CI"
  - git config user.email "noreply@travis-ci.org"
  - COMMIT_MESSAGE="Test Commit `date "+%Y-%m-%d %H:%M:%S"` from `git log -n 1 --format='commit %h - %s'`"

script:
  - set -e
  - bundle install
  - bundle exec jekyll build # Or jekyll build or whatever command you use to generate your site
  - git checkout gh-pages # Replace master with gh-pages if applicable
  - git add Gemfile.lock
  - git add -f _site/ # Replace _site/ with the build's output directory
  - 'git commit -m "${COMMIT_MESSAGE}"'
  #- git filter-branch -f --subdirectory-filter _site/ # Again, replace _site/
  # Obviously, replace with your repo's SSH URL and the appropriate branch
  - git push -v -f ssh://github.com/anantshri/manual_verification gh-pages:gh-pages

branches:
  only:
    - gh-pages

