language: ruby
rvm:
  - 2.1
install:
  - gem install jekyll
before_script:
  # Replace with the line that travis encrypt-file printed out
  -  openssl aes-256-cbc -K $encrypted_e9678b4a945e_key -iv $encrypted_e9678b4a945e_iv -in .travisdeploykey.enc -out .travisdeploykey -d
  - chmod go-rwx .travisdeploykey
  - eval `ssh-agent -s`
  - ssh-add .travisdeploykey
  - git config user.name "Travis-CI"
  - git config user.email "noreply@travis-ci.org"
  - COMMIT_MESSAGE="Publishing site on `date "+%Y-%m-%d %H:%M:%S"` from
    `git log -n 1 --format='commit %h - %s'`"

script:
  - set -e
  - jekyll build # Or jekyll build or whatever command you use to generate your site
  - git checkout -b gh-pages # Replace master with gh-pages if applicable
  - git add -f _site/ # Replace _site/ with the build's output directory
  - 'git commit -m "${COMMIT_MESSAGE}"'
  - git filter-branch -f --subdirectory-filter _site/ # Again, replace _site/
  # Obviously, replace with your repo's SSH URL and the appropriate branch
  - git push -f ssh://github.com/anantshri/manual_verification master:master

branches:
  only:
    - gh-pages

