title:        Manual Verification
tagline:      'Curated Collection of manual verification methods for various vulnerabilities'
author:
  name:       'Anant Shrivastava'
  email:      'anant@anantshri.info'
  twitter:      https://twitter.com/anantshri
  linkedin:     https://www.linkedin.com/in/anantshri
baseurl:  //anantshri.github.io/manual_verification
projectname: manual_verification
markdown:     kramdown
highlighter:    pygments
future:      true

exclude:
  - README.md
  - Makefile
  - Gemfile*
  - vendor/
  - gentemplate.sh
  - info.sublime-*