title:        Manual Verification
tagline:      'Curated Collection of manual verification methods for various vulnerabilities'
author:
  name:       'Anant Shrivastava'
  email:      'anant@anantshri.info'
baseurl:  //anantshri.github.io/manual_verification
projectname: manual_verification
markdown:     kramdown
highlighter:    pygments
future:      true
